### ISSUE TITLE
Having a /.../get/.../ URI

### ISSUE THREAD

**Issue by aRkadeFR** [samgiles/slumber#106]
Hello,

I didn't find any help on the documentation or in the submitted issues about this.

How can I do a request like:
```
api = slumber.Api()
api.master.object.get.prop.get()
```

so the api call the URI /master/object/get/prop/ ?

Thanks

**Comment by samgiles** [comment]
Does this (http://slumber.readthedocs.org/en/v0.6.0/tutorial.html#nested-resources) help?

**Comment by aRkadeFR** [comment]
nop sorry. I mean, how do you get the URL (for instance):
```
http://example.com/api/get/prop/toto/
```
?

Cause the get inside the URL will be the call to the method and not returning a new Resource.

**Comment by samgiles** [comment]
Yes, the documentation needs updating and I need to make release to PyPI a `.url()` method has been added to the Resource type.  I'll try and get round to making a release tonight :)

**Comment by aRkadeFR** [comment]
cool, thanks :+1:

**Comment by jhermann** [comment]
I'd also like to use `url()` with an "official" release, so here's a ping towards that release.  :sleeping: :boom: :smile: 

And if we can help in any way…

**Comment by samgiles** [comment]
0.7.0 release made. Sorry it took so long.

**Comment by jhermann** [comment]
Thanks a lot. :thumbsup:

**Comment by hadrien** [comment]
:+1: Thanks!

**Comment by aRkadeFR** [comment]
:+1:  Big thanks
