### ISSUE TITLE
URL parameter ?pass=secret

### ISSUE THREAD

**Issue by darkpixel** [samgiles/slumber#111]
Request Tracker only support authentication like:
```
https://rt.mydomain.com/REST/1.0/?user=joe&pass=123
```

Unfortunately ```pass``` is a reserved keyword in Python, so I can't call:
```
api.ticket(42).get(user='joe', pass='123')
```
...without python throwing an error.

I don't see any way around this in the docs.

**Comment by darkpixel** [comment]
Disregard.  I found a solution here: http://stackoverflow.com/questions/870455/soappy-reserved-word-in-named-parameter-list
```
auth = {'user': 'joe', 'pass', '123'}
api.ticket(42).get(**auth)
```

Might be useful for the documentation. :)

**Comment by samgiles** [comment]
The docs could certainly do with some love.  Glad you got it working.
