### ISSUE TITLE
Skip SSL verification

### ISSUE THREAD

**Issue by ceasaro** [samgiles/slumber#125]
Hi slumber,

I appreciate your library very much but i run into an issue, when i'm requesting a REST-API with an unverified SSL certificate. In the python requests module i have the opportunity set the verify parameter to False.
I missed this in your implementation i have created a clone of your project and implemented it myself. If you are interested you can take a look, it wasn't that much work :-)  

my clone is here: https://github.com/ceasaro/slumber_clone/commit/f410cfb6a78f6751ef64027a4580ec12133e66aa

kind regard,

Cees van Wieringen.

**Comment by jhermann** [comment]
You can pass in a configured requests session object. This makes way more sense that duplicating all of the requests API.

**Comment by ceasaro** [comment]
A thanks, for pointing this out to me. I somehow missed that option. It's way better :-)

**Comment by jhermann** [comment]
:bangbang: We had issues like this several times now, the docs should point this out very aggressively.

**Comment by samgiles** [comment]
fwiw, I'm working on rewriting the docs to be more concise and include things like this.
