### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by pombredanne** [samgiles/slumber#137]
@samgiles Is this is active or ?

**Comment by samgiles** [comment]
Hey, yes this is maintained.  However I am between jobs right now so don't have a dev machine.  Should be back up and running, and reviewing stuff in a couple weeks.

**Comment by pombredanne** [comment]
@samgiles thanks!

**Comment by RonnyPfannschmidt** [comment]
@samgiles im wondering, whats your opinion on adapting something like C4 and/or more maintainers

**Comment by pombredanne** [comment]
@RonnyPfannschmidt what do you mean by C4?

**Comment by samgiles** [comment]
Took longer than I'd hoped to start a new job, but tomorrow is my first day.  I'll have a machine at last!

I'm going to spend the week catching up on issues in this repo, clean it up a bit, and look at moving this into an organisation, or some other method of fostering a community.  I haven't done a great job of this so far, I aim to be better.

I like the principles of C4 (https://rfc.zeromq.org/spec:42/C4/), and I feel we can achieve something similar.
